import { describe, expect, it, vi } from "vitest";
import {
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError
} from "youtube-transcript-plus";

import {
  createYoutubeTranscriptProvider,
  getYoutubeTranscript,
  type YoutubeTranscriptProvider
} from "../packages/sources/src/index.js";

const VIDEO_ID = "XpZHKGGCK-o";
const NOW = new Date("2026-08-18T12:00:00.000Z");

const tracks = [
  { languageCode: "en", languageName: "English", isAutoGenerated: false },
  { languageCode: "es", languageName: "Spanish (auto-generated)", isAutoGenerated: true }
];

const transcript = {
  videoDetails: {
    videoId: VIDEO_ID,
    title: "A surprising implementation detail",
    author: "Recorded creator",
    channelId: "UC0123456789abcdefghijkl",
    lengthSeconds: 240,
    viewCount: 123,
    description: "Recorded description",
    keywords: ["recorded"],
    thumbnails: [],
    isLiveContent: false
  },
  segments: [
    { text: "First discovery", offset: 0, duration: 1.25, lang: "en" },
    { text: "Exact implementation", offset: 61.75, duration: 2, lang: "en" },
    { text: "Failure condition", offset: 125.1, duration: 3.4, lang: "en" }
  ]
};

function recordedProvider(): YoutubeTranscriptProvider {
  return {
    listLanguages: vi.fn(async () => tracks),
    fetchTranscript: vi.fn(async () => transcript)
  };
}

describe("YouTube transcript source adapter", () => {
  it("returns timestamped, language-provenanced pages and stays partial until exhausted", async () => {
    const firstProvider = recordedProvider();
    const first = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      language_code: "en",
      page_size: 2
    }, { provider: firstProvider, now: () => NOW });

    expect(first).toMatchObject({
      provider: "youtube",
      record_type: "youtube_transcript",
      primary_identifier: VIDEO_ID,
      retrieved_at: NOW.toISOString(),
      query: { video_id: VIDEO_ID, language_code: "en" },
      source_identity: {
        canonical_url: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
        title: "A surprising implementation detail",
        authors_or_channel: ["Recorded creator"]
      },
      pagination: { page_size: 2, returned: 2, exhausted: false },
      access_status: "partial",
      raw_metadata: {
        access_method: "youtube_innertube_unofficial",
        provider_reported_segments: 3,
        selected_track: {
          language_code: "en",
          language_name: "English",
          is_auto_generated: false
        },
        available_tracks: [
          { language_code: "en", language_name: "English", is_auto_generated: false },
          {
            language_code: "es",
            language_name: "Spanish (auto-generated)",
            is_auto_generated: true
          }
        ]
      },
      data: [
        {
          index: 0,
          start_ms: 0,
          duration_ms: 1250,
          text: "First discovery",
          language_code: "en",
          timestamp_url: `https://www.youtube.com/watch?v=${VIDEO_ID}&t=0s`
        },
        {
          index: 1,
          start_ms: 61750,
          duration_ms: 2000,
          text: "Exact implementation",
          language_code: "en",
          timestamp_url: `https://www.youtube.com/watch?v=${VIDEO_ID}&t=61s`
        }
      ]
    });
    expect(first.pagination.next_cursor).toMatch(/^[A-Za-z0-9_-]+$/u);
    expect(first.raw_metadata?.snapshot_sha256).toMatch(/^[a-f0-9]{64}$/u);
    expect(first.limitations.join(" ")).toContain("unofficial");
    expect(first.limitations.join(" ").toLowerCase()).toContain("caption accuracy");

    const second = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      cursor: first.pagination.next_cursor,
      page_size: 2
    }, { provider: recordedProvider(), now: () => NOW });

    expect(second).toMatchObject({
      query: { video_id: VIDEO_ID, language_code: "en" },
      pagination: {
        cursor: first.pagination.next_cursor,
        page_size: 2,
        returned: 1,
        exhausted: true
      },
      access_status: "api_visible_complete",
      data: [{
        index: 2,
        start_ms: 125100,
        duration_ms: 3400,
        text: "Failure condition",
        timestamp_url: `https://www.youtube.com/watch?v=${VIDEO_ID}&t=125s`
      }]
    });
    expect(second.pagination.next_cursor).toBeUndefined();
  });

  it("binds an opaque cursor to the video and selected language before provider access", async () => {
    const first = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      language_code: "en",
      page_size: 1
    }, { provider: recordedProvider(), now: () => NOW });
    const provider = recordedProvider();
    const mismatch = await getYoutubeTranscript({
      video_id_or_url: "W42rwWD6zjw",
      cursor: first.pagination.next_cursor
    }, { provider, now: () => NOW });

    expect(mismatch).toMatchObject({
      access_status: "error",
      error: {
        code: "youtube_transcript_cursor_mismatch",
        retryable: false
      },
      data: []
    });
    expect(provider.listLanguages).not.toHaveBeenCalled();
    expect(provider.fetchTranscript).not.toHaveBeenCalled();
  });

  it("fails closed instead of mixing caption revisions across cursor pages", async () => {
    const first = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      language_code: "en",
      page_size: 1
    }, { provider: recordedProvider(), now: () => NOW });
    const changedProvider = recordedProvider();
    changedProvider.fetchTranscript = vi.fn(async () => ({
      ...transcript,
      segments: transcript.segments.map((segment, index) => index === 0
        ? { ...segment, text: "Edited first discovery" }
        : segment)
    }));

    const changed = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      cursor: first.pagination.next_cursor
    }, { provider: changedProvider, now: () => NOW });

    expect(changed).toMatchObject({
      access_status: "error",
      pagination: { cursor: first.pagination.next_cursor, returned: 0, exhausted: false },
      error: {
        code: "youtube_transcript_snapshot_changed",
        retryable: false
      },
      data: []
    });
  });

  it("preserves provider-reported automatic-caption provenance for a selected track", async () => {
    const provider = recordedProvider();
    provider.fetchTranscript = vi.fn(async () => ({
      ...transcript,
      segments: transcript.segments.map((segment) => ({ ...segment, lang: "es" }))
    }));

    const result = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      language_code: "es"
    }, { provider, now: () => NOW });

    expect(result).toMatchObject({
      access_status: "api_visible_complete",
      raw_metadata: {
        selected_track: {
          language_code: "es",
          language_name: "Spanish (auto-generated)",
          is_auto_generated: true
        }
      }
    });
    expect(result.data).toHaveLength(3);
    expect(result.data.every(({ language_code }) => language_code === "es")).toBe(true);
    expect(result.limitations).toContain(
      "The selected track is provider-identified as automatically generated."
    );
  });

  it.each([
    [new YoutubeTranscriptDisabledError(VIDEO_ID), "inaccessible", "youtube_transcript_disabled", false],
    [new YoutubeTranscriptNotAvailableError(VIDEO_ID), "not_found", "youtube_transcript_not_available", false],
    [
      new YoutubeTranscriptNotAvailableLanguageError("fr", ["en", "es"], VIDEO_ID),
      "not_found",
      "youtube_transcript_language_not_available",
      false
    ],
    [new YoutubeTranscriptTooManyRequestError(), "rate_limited", "youtube_transcript_rate_limited", true],
    [new YoutubeTranscriptVideoUnavailableError(VIDEO_ID), "inaccessible", "youtube_transcript_video_unavailable", false]
  ] as const)("maps %s to literal access status %s", async (error, status, code, retryable) => {
    const provider: YoutubeTranscriptProvider = {
      listLanguages: vi.fn(async () => { throw error; }),
      fetchTranscript: vi.fn(async () => transcript)
    };
    const result = await getYoutubeTranscript({ video_id_or_url: VIDEO_ID }, {
      provider,
      now: () => NOW
    });

    expect(result).toMatchObject({
      access_status: status,
      error: { code, retryable },
      pagination: { returned: 0, exhausted: false },
      data: []
    });
  });

  it("rejects malformed transcript timing instead of laundering invalid provider output", async () => {
    const provider = recordedProvider();
    provider.fetchTranscript = vi.fn(async () => ({
      ...transcript,
      segments: [{ text: "Bad", offset: Number.NaN, duration: 1, lang: "en" }]
    }));

    const result = await getYoutubeTranscript({ video_id_or_url: VIDEO_ID }, {
      provider,
      now: () => NOW
    });

    expect(result).toMatchObject({
      access_status: "error",
      error: { code: "youtube_transcript_response_invalid", retryable: false },
      data: []
    });
  });

  it("transport-bounds a large transcript page without changing total-segment provenance", async () => {
    const provider = recordedProvider();
    provider.fetchTranscript = vi.fn(async () => ({
      ...transcript,
      segments: Array.from({ length: 200 }, (_, index) => ({
        text: `${index}: ${"bounded transcript text ".repeat(24)}`,
        offset: index * 2,
        duration: 1.5,
        lang: "en"
      }))
    }));

    const result = await getYoutubeTranscript({
      video_id_or_url: VIDEO_ID,
      page_size: 200
    }, { provider, now: () => NOW });

    expect(result.access_status).toBe("partial");
    expect(result.pagination.next_cursor).toBeDefined();
    expect(result.raw_metadata?.provider_reported_segments).toBe(200);
    expect(result.data.length).toBeGreaterThan(0);
    expect(result.data.length).toBeLessThan(200);
    expect(new TextEncoder().encode(JSON.stringify(result)).byteLength)
      .toBeLessThanOrEqual(50_000);
  });

  it("preserves an upstream 429 as rate_limited before the library can relabel it", async () => {
    const provider = createYoutubeTranscriptProvider({
      fetchImpl: vi.fn(async () => new Response("limited", { status: 429 }))
    });

    const result = await getYoutubeTranscript({ video_id_or_url: VIDEO_ID }, {
      provider,
      now: () => NOW
    });

    expect(result).toMatchObject({
      access_status: "rate_limited",
      error: { code: "youtube_transcript_rate_limited", retryable: true },
      data: []
    });
  });

  it("reports a request deadline as a retryable error instead of negative evidence", async () => {
    const provider: YoutubeTranscriptProvider = {
      listLanguages: vi.fn(async () => {
        throw new DOMException("deadline", "TimeoutError");
      }),
      fetchTranscript: vi.fn(async () => transcript)
    };

    const result = await getYoutubeTranscript({ video_id_or_url: VIDEO_ID }, {
      provider,
      now: () => NOW
    });

    expect(result).toMatchObject({
      access_status: "error",
      error: { code: "youtube_transcript_timeout", retryable: true },
      data: []
    });
  });

  it("allows only bounded HTTPS YouTube responses through the adopted provider", async () => {
    const requests: URL[] = [];
    const fetchImpl = vi.fn(async (input: URL | RequestInfo) => {
      const url = new URL(String(input));
      requests.push(url);
      if (requests.length === 1) {
        return new Response('<html>"INNERTUBE_API_KEY":"recorded-key"</html>');
      }
      if (requests.length === 2) {
        return new Response(JSON.stringify({
          playabilityStatus: { status: "OK" },
          captions: {
            playerCaptionsTracklistRenderer: {
              captionTracks: [{
                baseUrl: "https://captions.evil.example/api/timedtext",
                languageCode: "en",
                name: { simpleText: "English" }
              }]
            }
          },
          videoDetails: { videoId: VIDEO_ID }
        }), { headers: { "content-type": "application/json" } });
      }
      throw new Error("unexpected request");
    });
    const provider = createYoutubeTranscriptProvider({ fetchImpl });

    await expect(provider.fetchTranscript(VIDEO_ID, {
      languageCode: "en",
      signal: new AbortController().signal
    })).rejects.toThrow("Upstream host is not allowlisted");
    expect(requests.map(({ origin }) => origin)).toEqual([
      "https://www.youtube.com",
      "https://www.youtube.com"
    ]);
  });

  it("fails closed before consuming a provider body declared above the response limit", async () => {
    const body = vi.fn(async () => "should not be consumed");
    const fetchImpl = vi.fn(async () => ({
      ok: true,
      status: 200,
      statusText: "OK",
      headers: new Headers({ "content-length": "2048" }),
      body: null,
      text: body
    } as unknown as Response));
    const provider = createYoutubeTranscriptProvider({
      fetchImpl,
      maxResponseBytes: 1024
    });

    await expect(provider.listLanguages(VIDEO_ID, {
      signal: new AbortController().signal
    })).rejects.toThrow("Upstream response exceeds 1024 bytes");
    expect(body).not.toHaveBeenCalled();
  });
});
