import {
  fetchTranscript as fetchProviderTranscript,
  listLanguages as listProviderLanguages,
  type CaptionTrackInfo,
  type FetchParams,
  type TranscriptResult
} from "youtube-transcript-plus";
import {
  ACCESS_STATUSES,
  errorEnvelope,
  okEnvelope,
  type AccessStatus,
  type ProvenanceEnvelope
} from "@askrigor/contracts";
import { z } from "zod";

import { decodeCursor, encodeCursor } from "./cursor.js";
import { parseYoutubeVideoId, youtubeVideoIdSchema } from "./youtube.js";

const DEFAULT_PAGE_SIZE = 100;
const MAX_PAGE_SIZE = 200;
const DEFAULT_TIMEOUT_MS = 20_000;
const DEFAULT_MAX_UPSTREAM_RESPONSE_BYTES = 10 * 1_024 * 1_024;
const ACTION_SAFE_RESPONSE_BYTES = 50_000;
const MAX_TRACKS = 100;
const TRANSCRIPT_PROVIDER_HOSTS = new Set(["www.youtube.com"]);

const TRANSCRIPT_LIMITATIONS = [
  "Transcript retrieval uses an unofficial YouTube Innertube interface and may be unavailable or break independently of browser-visible captions.",
  "Completeness covers only the selected API-visible caption track, not other languages, deleted or inaccessible captions, uncaptured speech, on-screen text, or later edits.",
  "Caption accuracy is not independently verified; automatic captions can misstate words, timing, speakers, quantities, or technical terms."
] as const;

const languageCodeSchema = z.string()
  .min(2)
  .max(35)
  .regex(/^[A-Za-z]{2,8}(?:-[A-Za-z0-9]{1,8})*$/u);

export const youtubeTranscriptInputSchema = z.object({
  video_id_or_url: z.string().min(1).max(2_048),
  language_code: languageCodeSchema.optional(),
  cursor: z.string().min(1).max(4_096).optional(),
  page_size: z.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE)
}).strict();

export const youtubeTranscriptTrackSchema = z.object({
  language_code: languageCodeSchema,
  language_name: z.string().min(1).max(500),
  is_auto_generated: z.boolean()
}).strict();

export const youtubeTranscriptSegmentSchema = z.object({
  index: z.number().int().nonnegative(),
  start_ms: z.number().int().nonnegative(),
  duration_ms: z.number().int().nonnegative(),
  text: z.string().min(1).max(20_000),
  language_code: languageCodeSchema,
  timestamp_url: z.string().url()
}).strict();

const transcriptErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  http_status: z.number().int().optional(),
  retryable: z.boolean().optional()
}).strict();

const transcriptRawMetadataSchema = z.object({
  access_method: z.literal("youtube_innertube_unofficial"),
  provider_reported_segments: z.number().int().nonnegative().optional(),
  snapshot_sha256: z.string().regex(/^[a-f0-9]{64}$/u).optional(),
  selected_track: youtubeTranscriptTrackSchema.optional(),
  available_tracks: z.array(youtubeTranscriptTrackSchema).max(MAX_TRACKS)
}).strict();

export const youtubeTranscriptEnvelopeSchema = z.object({
  provider: z.literal("youtube"),
  record_type: z.literal("youtube_transcript"),
  primary_identifier: youtubeVideoIdSchema.optional(),
  retrieved_at: z.string(),
  query: z.object({
    video_id: youtubeVideoIdSchema,
    language_code: languageCodeSchema.optional()
  }).strict().optional(),
  source_identity: z.object({
    canonical_url: z.string().url().optional(),
    title: z.string().max(10_000).optional(),
    authors_or_channel: z.array(z.string().max(10_000)).optional()
  }).strict(),
  pagination: z.object({
    cursor: z.string().optional(),
    next_cursor: z.string().optional(),
    page_size: z.number().int().min(1).max(MAX_PAGE_SIZE).optional(),
    returned: z.number().int().nonnegative(),
    exhausted: z.boolean()
  }).strict(),
  access_status: z.enum(ACCESS_STATUSES),
  limitations: z.array(z.string()),
  raw_metadata: transcriptRawMetadataSchema.optional(),
  error: transcriptErrorSchema.optional(),
  data: z.array(youtubeTranscriptSegmentSchema).max(MAX_PAGE_SIZE)
}).strict();

const providerTrackSchema = z.object({
  languageCode: languageCodeSchema,
  languageName: z.string().min(1).max(500),
  isAutoGenerated: z.boolean()
}).strict();

const providerTranscriptSchema = z.object({
  videoDetails: z.object({
    videoId: youtubeVideoIdSchema,
    title: z.string().max(10_000),
    author: z.string().max(10_000),
    channelId: z.string().max(512),
    lengthSeconds: z.number().int().nonnegative(),
    viewCount: z.number().int().nonnegative(),
    description: z.string().max(1_000_000),
    keywords: z.array(z.string().max(500)),
    thumbnails: z.array(z.object({
      url: z.string(),
      width: z.number(),
      height: z.number()
    }).passthrough()),
    isLiveContent: z.boolean()
  }).strict(),
  segments: z.array(z.object({
    text: z.string().min(1).max(20_000),
    duration: z.number().finite().nonnegative(),
    offset: z.number().finite().nonnegative(),
    lang: languageCodeSchema
  }).strict()).min(1)
}).strict();

const transcriptCursorSchema = z.object({
  v: z.literal(1),
  video_id: youtubeVideoIdSchema,
  language_code: languageCodeSchema,
  snapshot_sha256: z.string().regex(/^[a-f0-9]{64}$/u),
  offset: z.number().int().positive()
}).strict();

export type YoutubeTranscriptInput = z.input<typeof youtubeTranscriptInputSchema>;
export type YoutubeTranscriptEnvelope = z.output<typeof youtubeTranscriptEnvelopeSchema>;

export interface YoutubeTranscriptProviderRequest {
  languageCode?: string;
  signal: AbortSignal;
}

export interface YoutubeTranscriptProvider {
  listLanguages(
    videoId: string,
    request: Omit<YoutubeTranscriptProviderRequest, "languageCode">
  ): Promise<CaptionTrackInfo[]>;
  fetchTranscript(
    videoId: string,
    request: YoutubeTranscriptProviderRequest & { languageCode: string }
  ): Promise<TranscriptResult>;
}

export interface YoutubeTranscriptProviderOptions {
  fetchImpl?: typeof fetch;
  maxResponseBytes?: number;
  timeoutMs?: number;
}

export interface YoutubeTranscriptRuntime {
  provider?: YoutubeTranscriptProvider;
  now?: () => Date;
  timeoutMs?: number;
}

export function createYoutubeTranscriptProvider(
  options: YoutubeTranscriptProviderOptions = {}
): YoutubeTranscriptProvider {
  const fetchImpl = options.fetchImpl ?? fetch;
  const maxResponseBytes = options.maxResponseBytes ??
    DEFAULT_MAX_UPSTREAM_RESPONSE_BYTES;
  const timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  if (!Number.isSafeInteger(maxResponseBytes) || maxResponseBytes < 1) {
    throw new Error("YouTube transcript response limit is invalid");
  }
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 1) {
    throw new Error("YouTube transcript timeout is invalid");
  }

  const providerFetch = async (params: FetchParams): Promise<Response> =>
    boundedYoutubeFetch(params, { fetchImpl, maxResponseBytes, timeoutMs });

  const providerConfig = (signal: AbortSignal) => ({
    videoFetch: providerFetch,
    playerFetch: providerFetch,
    transcriptFetch: providerFetch,
    retries: 0,
    signal
  });

  return {
    async listLanguages(videoId, { signal }) {
      return listProviderLanguages(videoId, providerConfig(signal));
    },
    async fetchTranscript(videoId, { languageCode, signal }) {
      return fetchProviderTranscript(videoId, {
        ...providerConfig(signal),
        lang: languageCode,
        videoDetails: true
      });
    }
  };
}

export async function getYoutubeTranscript(
  input: YoutubeTranscriptInput,
  runtime: YoutubeTranscriptRuntime = {}
): Promise<YoutubeTranscriptEnvelope> {
  const parsedInput = youtubeTranscriptInputSchema.safeParse(input);
  if (!parsedInput.success) {
    return transcriptFailure("youtube_transcript_input_invalid", undefined, runtime);
  }
  const videoId = parseYoutubeVideoId(parsedInput.data.video_id_or_url);
  if (videoId === undefined) {
    return transcriptFailure("youtube_video_id_invalid", undefined, runtime);
  }

  const cursorResult = parseTranscriptCursor(parsedInput.data.cursor);
  if (cursorResult.error !== undefined) {
    return transcriptFailure(cursorResult.error, videoId, runtime, parsedInput.data);
  }
  const cursor = cursorResult.cursor;
  if (
    cursor !== undefined &&
    (
      cursor.video_id !== videoId ||
      (
        parsedInput.data.language_code !== undefined &&
        parsedInput.data.language_code !== cursor.language_code
      )
    )
  ) {
    return transcriptFailure(
      "youtube_transcript_cursor_mismatch",
      videoId,
      runtime,
      parsedInput.data
    );
  }

  const languageCode = cursor?.language_code ?? parsedInput.data.language_code;
  const timeoutMs = runtime.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 1) {
    return transcriptFailure(
      "youtube_transcript_runtime_invalid",
      videoId,
      runtime,
      parsedInput.data
    );
  }
  const signal = AbortSignal.timeout(timeoutMs);
  const provider = runtime.provider ?? createYoutubeTranscriptProvider({ timeoutMs });

  let availableTracks: z.output<typeof youtubeTranscriptTrackSchema>[] = [];
  try {
    const parsedTracks = z.array(providerTrackSchema).min(1).max(MAX_TRACKS).safeParse(
      await provider.listLanguages(videoId, { signal })
    );
    if (!parsedTracks.success) throw new YoutubeTranscriptResponseError();
    availableTracks = parsedTracks.data.map(normalizeTrack);
    const selectedTrack = languageCode === undefined
      ? availableTracks[0]
      : availableTracks.find((track) => track.language_code === languageCode);
    if (selectedTrack === undefined) {
      return transcriptFailure(
        "youtube_transcript_language_not_available",
        videoId,
        runtime,
        parsedInput.data,
        availableTracks
      );
    }

    const parsedTranscript = providerTranscriptSchema.safeParse(
      await provider.fetchTranscript(videoId, {
        languageCode: selectedTrack.language_code,
        signal
      })
    );
    if (
      !parsedTranscript.success ||
      parsedTranscript.data.videoDetails.videoId !== videoId ||
      parsedTranscript.data.segments.some(({ lang }) => lang !== selectedTrack.language_code)
    ) {
      throw new YoutubeTranscriptResponseError();
    }
    const snapshotSha256 = await transcriptSnapshotSha256(
      selectedTrack,
      parsedTranscript.data.segments
    );
    if (cursor !== undefined && cursor.snapshot_sha256 !== snapshotSha256) {
      return transcriptFailure(
        "youtube_transcript_snapshot_changed",
        videoId,
        runtime,
        parsedInput.data,
        availableTracks
      );
    }

    const offset = cursor?.offset ?? 0;
    if (offset >= parsedTranscript.data.segments.length) {
      return transcriptFailure(
        "youtube_transcript_cursor_invalid",
        videoId,
        runtime,
        parsedInput.data,
        availableTracks
      );
    }
    return successfulTranscriptPage({
      videoId,
      cursor: parsedInput.data.cursor,
      offset,
      pageSize: parsedInput.data.page_size,
      snapshotSha256,
      selectedTrack,
      availableTracks,
      transcript: parsedTranscript.data,
      retrievedAt: readRetrievedAt(runtime)
    });
  } catch (error) {
    return transcriptFailure(
      transcriptFailureCode(error),
      videoId,
      runtime,
      parsedInput.data,
      availableTracks,
      error
    );
  }
}

interface SuccessfulPageInput {
  videoId: string;
  cursor?: string;
  offset: number;
  pageSize: number;
  snapshotSha256: string;
  selectedTrack: z.output<typeof youtubeTranscriptTrackSchema>;
  availableTracks: z.output<typeof youtubeTranscriptTrackSchema>[];
  transcript: z.output<typeof providerTranscriptSchema>;
  retrievedAt: string;
}

function successfulTranscriptPage(input: SuccessfulPageInput): YoutubeTranscriptEnvelope {
  const maximumCount = Math.min(
    input.pageSize,
    input.transcript.segments.length - input.offset
  );
  for (let count = maximumCount; count >= 1; count -= 1) {
    const data = input.transcript.segments
      .slice(input.offset, input.offset + count)
      .map((segment, index) => normalizeSegment(
        segment,
        input.videoId,
        input.offset + index
      ));
    const exhausted = input.offset + count === input.transcript.segments.length;
    const limitations = [
      ...TRANSCRIPT_LIMITATIONS,
      ...(input.selectedTrack.is_auto_generated
        ? ["The selected track is provider-identified as automatically generated."]
        : []),
      ...(!exhausted
        ? ["A continuation re-fetches the selected track and must match this page's caption snapshot SHA-256."]
        : [])
    ];
    const envelope = okEnvelope({
      provider: "youtube",
      recordType: "youtube_transcript",
      primaryIdentifier: input.videoId,
      retrievedAt: input.retrievedAt,
      query: {
        video_id: input.videoId,
        language_code: input.selectedTrack.language_code
      },
      sourceIdentity: {
        canonical_url: `https://www.youtube.com/watch?v=${input.videoId}`,
        ...(input.transcript.videoDetails.title.length === 0
          ? {}
          : { title: input.transcript.videoDetails.title }),
        ...(input.transcript.videoDetails.author.length === 0
          ? {}
          : { authors_or_channel: [input.transcript.videoDetails.author] })
      },
      pagination: {
        ...(input.cursor === undefined ? {} : { cursor: input.cursor }),
        ...(!exhausted
          ? {
              next_cursor: encodeCursor({
                v: 1,
                video_id: input.videoId,
                language_code: input.selectedTrack.language_code,
                snapshot_sha256: input.snapshotSha256,
                offset: input.offset + count
              })
            }
          : {}),
        page_size: input.pageSize,
        exhausted
      },
      accessStatus: exhausted ? "api_visible_complete" : "partial",
      limitations,
      rawMetadata: {
        access_method: "youtube_innertube_unofficial",
        provider_reported_segments: input.transcript.segments.length,
        snapshot_sha256: input.snapshotSha256,
        selected_track: input.selectedTrack,
        available_tracks: input.availableTracks
      },
      returned: data.length,
      data
    });
    const parsed = youtubeTranscriptEnvelopeSchema.safeParse(envelope);
    if (
      parsed.success &&
      new TextEncoder().encode(JSON.stringify(parsed.data)).byteLength <=
        ACTION_SAFE_RESPONSE_BYTES
    ) {
      return parsed.data;
    }
  }
  return transcriptFailure(
    "youtube_transcript_segment_too_large",
    input.videoId,
    { now: () => new Date(input.retrievedAt) },
    { video_id_or_url: input.videoId, page_size: input.pageSize },
    input.availableTracks
  );
}

function normalizeTrack(
  track: z.output<typeof providerTrackSchema>
): z.output<typeof youtubeTranscriptTrackSchema> {
  return {
    language_code: track.languageCode,
    language_name: track.languageName,
    is_auto_generated: track.isAutoGenerated
  };
}

function normalizeSegment(
  segment: z.output<typeof providerTranscriptSchema>["segments"][number],
  videoId: string,
  index: number
): z.output<typeof youtubeTranscriptSegmentSchema> {
  const startMs = Math.round(segment.offset * 1_000);
  return {
    index,
    start_ms: startMs,
    duration_ms: Math.round(segment.duration * 1_000),
    text: segment.text,
    language_code: segment.lang,
    timestamp_url: `https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(startMs / 1_000)}s`
  };
}

async function transcriptSnapshotSha256(
  selectedTrack: z.output<typeof youtubeTranscriptTrackSchema>,
  segments: z.output<typeof providerTranscriptSchema>["segments"]
): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(JSON.stringify({ selected_track: selectedTrack, segments }))
  );
  return Array.from(
    new Uint8Array(digest),
    (byte) => byte.toString(16).padStart(2, "0")
  ).join("");
}

function parseTranscriptCursor(cursor: string | undefined): {
  cursor?: z.output<typeof transcriptCursorSchema>;
  error?: "youtube_transcript_cursor_invalid";
} {
  if (cursor === undefined) return {};
  try {
    const parsed = transcriptCursorSchema.safeParse(decodeCursor(cursor));
    return parsed.success
      ? { cursor: parsed.data }
      : { error: "youtube_transcript_cursor_invalid" };
  } catch {
    return { error: "youtube_transcript_cursor_invalid" };
  }
}

type TranscriptFailureCode =
  | "youtube_transcript_input_invalid"
  | "youtube_video_id_invalid"
  | "youtube_transcript_cursor_invalid"
  | "youtube_transcript_cursor_mismatch"
  | "youtube_transcript_snapshot_changed"
  | "youtube_transcript_runtime_invalid"
  | "youtube_transcript_disabled"
  | "youtube_transcript_not_available"
  | "youtube_transcript_language_not_available"
  | "youtube_transcript_rate_limited"
  | "youtube_transcript_timeout"
  | "youtube_transcript_video_unavailable"
  | "youtube_transcript_response_invalid"
  | "youtube_transcript_segment_too_large"
  | "youtube_transcript_failed";

function transcriptFailureCode(error: unknown): TranscriptFailureCode {
  const name = providerErrorName(error);
  if (name === "YoutubeTranscriptDisabledError") {
    return "youtube_transcript_disabled";
  }
  if (name === "YoutubeTranscriptNotAvailableLanguageError") {
    return "youtube_transcript_language_not_available";
  }
  if (name === "YoutubeTranscriptNotAvailableError") {
    return "youtube_transcript_not_available";
  }
  if (
    name === "YoutubeTranscriptTooManyRequestError" ||
    error instanceof YoutubeTranscriptUpstreamRateLimitedError
  ) {
    return "youtube_transcript_rate_limited";
  }
  if (name === "TimeoutError" || name === "AbortError") {
    return "youtube_transcript_timeout";
  }
  if (name === "YoutubeTranscriptVideoUnavailableError") {
    return "youtube_transcript_video_unavailable";
  }
  if (error instanceof YoutubeTranscriptResponseError) {
    return "youtube_transcript_response_invalid";
  }
  if (
    name === "YoutubeTranscriptInvalidLangError" ||
    name === "YoutubeTranscriptInvalidVideoIdError"
  ) {
    return "youtube_transcript_response_invalid";
  }
  return "youtube_transcript_failed";
}

const FAILURE_DETAILS: Record<TranscriptFailureCode, {
  accessStatus: AccessStatus;
  message: string;
  retryable: boolean;
}> = {
  youtube_transcript_input_invalid: {
    accessStatus: "error",
    message: "YouTube transcript input is invalid",
    retryable: false
  },
  youtube_video_id_invalid: {
    accessStatus: "error",
    message: "YouTube video identifier is invalid",
    retryable: false
  },
  youtube_transcript_cursor_invalid: {
    accessStatus: "error",
    message: "YouTube transcript cursor is invalid; restart from the video identifier",
    retryable: false
  },
  youtube_transcript_cursor_mismatch: {
    accessStatus: "error",
    message: "YouTube transcript cursor does not match the requested video or language",
    retryable: false
  },
  youtube_transcript_snapshot_changed: {
    accessStatus: "error",
    message: "The selected caption track changed; restart from the video identifier and language",
    retryable: false
  },
  youtube_transcript_runtime_invalid: {
    accessStatus: "error",
    message: "YouTube transcript runtime is invalid",
    retryable: false
  },
  youtube_transcript_disabled: {
    accessStatus: "inaccessible",
    message: "YouTube reports that transcripts are disabled for this video",
    retryable: false
  },
  youtube_transcript_not_available: {
    accessStatus: "not_found",
    message: "No API-visible transcript was available for this video",
    retryable: false
  },
  youtube_transcript_language_not_available: {
    accessStatus: "not_found",
    message: "The requested transcript language was not available",
    retryable: false
  },
  youtube_transcript_rate_limited: {
    accessStatus: "rate_limited",
    message: "YouTube rate-limited transcript retrieval",
    retryable: true
  },
  youtube_transcript_timeout: {
    accessStatus: "error",
    message: "YouTube transcript retrieval exceeded its request deadline",
    retryable: true
  },
  youtube_transcript_video_unavailable: {
    accessStatus: "inaccessible",
    message: "The video was unavailable to transcript retrieval",
    retryable: false
  },
  youtube_transcript_response_invalid: {
    accessStatus: "error",
    message: "YouTube transcript response was invalid",
    retryable: false
  },
  youtube_transcript_segment_too_large: {
    accessStatus: "partial",
    message: "A transcript segment could not fit the bounded Action response",
    retryable: false
  },
  youtube_transcript_failed: {
    accessStatus: "error",
    message: "YouTube transcript retrieval failed",
    retryable: true
  }
};

function transcriptFailure(
  code: TranscriptFailureCode,
  videoId: string | undefined,
  runtime: YoutubeTranscriptRuntime,
  input?: Partial<z.output<typeof youtubeTranscriptInputSchema>>,
  availableTracks: z.output<typeof youtubeTranscriptTrackSchema>[] = [],
  error?: unknown
): YoutubeTranscriptEnvelope {
  const details = FAILURE_DETAILS[code];
  const languageFailure = unavailableLanguageDetails(error);
  const languageFromError = languageFailure?.lang;
  const languagesFromError = languageFailure === undefined
    ? []
    : languageFailure.availableLangs.map((languageCode: string) => ({
        language_code: languageCode,
        language_name: languageCode,
        is_auto_generated: false
      })).filter((track: unknown) => youtubeTranscriptTrackSchema.safeParse(track).success);
  const tracks = availableTracks.length > 0 ? availableTracks : languagesFromError;
  const envelope = errorEnvelope<[]>(
    {
      provider: "youtube",
      recordType: "youtube_transcript",
      ...(videoId === undefined ? {} : { primaryIdentifier: videoId }),
      retrievedAt: readRetrievedAt(runtime),
      ...(videoId === undefined
        ? {}
        : {
            query: {
              video_id: videoId,
              ...((input?.language_code ?? languageFromError) === undefined
                ? {}
                : { language_code: input?.language_code ?? languageFromError })
            }
          }),
      sourceIdentity: videoId === undefined
        ? {}
        : { canonical_url: `https://www.youtube.com/watch?v=${videoId}` },
      pagination: {
        ...(input?.cursor === undefined ? {} : { cursor: input.cursor }),
        ...(input?.page_size === undefined ? {} : { page_size: input.page_size }),
        exhausted: false
      },
      accessStatus: details.accessStatus,
      limitations: [...TRANSCRIPT_LIMITATIONS],
      rawMetadata: {
        access_method: "youtube_innertube_unofficial",
        available_tracks: tracks
      },
      code,
      message: details.message,
      retryable: details.retryable,
      data: []
    }
  );
  return youtubeTranscriptEnvelopeSchema.parse(envelope);
}

function readRetrievedAt(runtime: YoutubeTranscriptRuntime): string {
  try {
    const value = runtime.now?.() ?? new Date();
    if (!(value instanceof Date) || Number.isNaN(value.valueOf())) throw new Error();
    return value.toISOString();
  } catch {
    return new Date(0).toISOString();
  }
}

interface BoundedFetchOptions {
  fetchImpl: typeof fetch;
  maxResponseBytes: number;
  timeoutMs: number;
}

async function boundedYoutubeFetch(
  params: FetchParams,
  options: BoundedFetchOptions
): Promise<Response> {
  const url = validateTranscriptUrl(params.url);
  const timeoutSignal = AbortSignal.timeout(options.timeoutMs);
  const signal = params.signal === undefined
    ? timeoutSignal
    : AbortSignal.any([params.signal, timeoutSignal]);
  const response = await options.fetchImpl(url.toString(), {
    method: params.method ?? "GET",
    ...(params.body === undefined ? {} : { body: params.body }),
    headers: params.headers,
    redirect: "error",
    signal
  });
  if (response.status === 429) {
    await response.body?.cancel();
    throw new YoutubeTranscriptUpstreamRateLimitedError();
  }
  const declaredLength = Number(response.headers.get("content-length"));
  if (Number.isFinite(declaredLength) && declaredLength > options.maxResponseBytes) {
    await response.body?.cancel();
    throw new Error(`Upstream response exceeds ${options.maxResponseBytes} bytes`);
  }
  const bytes = await readBoundedBody(response, options.maxResponseBytes);
  return new Response(bytes.length === 0 ? null : new TextDecoder().decode(bytes), {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers
  });
}

function validateTranscriptUrl(value: string): URL {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new Error("Invalid upstream URL");
  }
  if (url.protocol !== "https:") throw new Error("Upstream URL must use HTTPS");
  if (!TRANSCRIPT_PROVIDER_HOSTS.has(url.hostname)) {
    throw new Error("Upstream host is not allowlisted");
  }
  if (url.username.length > 0 || url.password.length > 0) {
    throw new Error("Upstream URL must not include credentials");
  }
  return url;
}

async function readBoundedBody(response: Response, maximumBytes: number): Promise<Uint8Array> {
  const reader = response.body?.getReader();
  if (reader === undefined) return new Uint8Array();
  const chunks: Uint8Array[] = [];
  let bytes = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      bytes += value.byteLength;
      if (bytes > maximumBytes) {
        await reader.cancel();
        throw new Error(`Upstream response exceeds ${maximumBytes} bytes`);
      }
      chunks.push(value);
    }
  } finally {
    reader.releaseLock();
  }
  const result = new Uint8Array(bytes);
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return result;
}

class YoutubeTranscriptResponseError extends Error {}
class YoutubeTranscriptUpstreamRateLimitedError extends Error {}

function providerErrorName(error: unknown): string | undefined {
  if (!(error instanceof Error)) return undefined;
  if (error.name === "TimeoutError" || error.name === "AbortError") {
    return error.name;
  }
  return error.constructor.name;
}

function unavailableLanguageDetails(error: unknown): {
  lang: string;
  availableLangs: string[];
} | undefined {
  if (
    providerErrorName(error) !== "YoutubeTranscriptNotAvailableLanguageError" ||
    typeof error !== "object" ||
    error === null
  ) {
    return undefined;
  }
  const record = error as Record<string, unknown>;
  if (
    typeof record.lang !== "string" ||
    !Array.isArray(record.availableLangs) ||
    !record.availableLangs.every((value) => typeof value === "string")
  ) {
    return undefined;
  }
  return { lang: record.lang, availableLangs: record.availableLangs as string[] };
}

export type YoutubeTranscriptProvenance = ProvenanceEnvelope<
  z.output<typeof youtubeTranscriptSegmentSchema>[]
>;
